export interface SeedProduct {
  nameEn: string
  nameTl: string
  slug: string
  descriptionEn: string
  descriptionTl: string
  price: number
  image: string
  categorySlug: string
  inventory: number
  vendor: string
}

export const products: SeedProduct[] = [
  // — Chichirya: Classic Snacks (4) —
  {
    nameEn: 'Oishii Crackers (pack)',
    nameTl: 'Oishii Crackers',
    slug: 'oishii',
    descriptionEn: 'Classic round crackers in the iconic pink pack. Perfect snack for merienda.',
    descriptionTl: 'Sikat na bilog na crackers na nasa pink na pack. Paboritong meryenda ng bata at matanda.',
    price: 200,
    image: 'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=600&h=400&fit=crop',
    categorySlug: 'chichirya',
    inventory: 50,
    vendor: "Aling Nena's Sari-Sari",
  },
  {
    nameEn: 'Nooda Crunch (Chicken)',
    nameTl: 'Nooda Crunch',
    slug: 'nooda-crunch',
    descriptionEn: 'Crunchy chicken-flavored noodle snack. A classic from childhood.',
    descriptionTl: 'Malutong na noodle snack na lasang manok. Klasikong meryenda ng kabataan.',
    price: 500,
    image: 'https://images.unsplash.com/photo-1572802419224-296b0aeee0d9?w=600&h=400&fit=crop',
    categorySlug: 'chichirya',
    inventory: 40,
    vendor: "Aling Nena's Sari-Sari",
  },
  {
    nameEn: 'Tattoos Corn Chips (BBQ)',
    nameTl: 'Tattoos Corn Chips',
    slug: 'tattoos',
    descriptionEn: 'Crunchy corn chips with BBQ flavor. Comes with a temporary tattoo inside!',
    descriptionTl: 'Malutong na corn chips na BBQ flavor. May temporary tattoo sa loob!',
    price: 600,
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&h=400&fit=crop',
    categorySlug: 'chichirya',
    inventory: 35,
    vendor: "Aling Nena's Sari-Sari",
  },
  {
    nameEn: 'Pritos Ring (Onion)',
    nameTl: 'Pritos Ring',
    slug: 'pritos-ring',
    descriptionEn: 'Onion-flavored ring-shaped snack. Crunchy and addictive.',
    descriptionTl: 'Meryenda na hugis singsing, lasang sibuyas. Malutong at nakakaadik.',
    price: 700,
    image: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=600&h=400&fit=crop',
    categorySlug: 'chichirya',
    inventory: 30,
    vendor: "Aling Nena's Sari-Sari",
  },

  // — Noodles & Pantry (4) —
  {
    nameEn: 'Lucky Me! Pancit Canton (Sweet & Spicy)',
    nameTl: 'Pancit Canton (Sweet & Spicy)',
    slug: 'pancit-canton',
    descriptionEn: 'The ultimate instant pancit canton. Ready in 3 minutes. Sweet & Spicy flavor.',
    descriptionTl: 'Ang ultimate na instant pancit canton. Luto sa 3 minuto. Sweet & Spicy flavor.',
    price: 1500,
    image: '/images/products/pancit-canton.jpg',
    categorySlug: 'noodles-pantry',
    inventory: 60,
    vendor: "Aling Nena's Sari-Sari",
  },
  {
    nameEn: 'Payless Xtra Big (Chicken)',
    nameTl: 'Payless Xtra Big',
    slug: 'payless',
    descriptionEn: 'Extra big serving of chicken-flavored instant noodles. Perfect for sharing.',
    descriptionTl: 'Malaking serving ng instant noodles na lasang manok. Pwedeng pangkasalo.',
    price: 1200,
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&h=400&fit=crop',
    categorySlug: 'noodles-pantry',
    inventory: 45,
    vendor: "Aling Nena's Sari-Sari",
  },
  {
    nameEn: 'Nissin Cup Noodles (Seafood)',
    nameTl: 'Nissin Cup Noodles',
    slug: 'nissin-cup',
    descriptionEn: 'Classic cup noodles with seafood flavor. Just add hot water!',
    descriptionTl: 'Klasikong cup noodles na seafood flavor. Mainit na tubig lang, ok na!',
    price: 2000,
    image: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=600&h=400&fit=crop',
    categorySlug: 'noodles-pantry',
    inventory: 30,
    vendor: "Aling Nena's Sari-Sari",
  },
  {
    nameEn: 'Argentina Corned Beef (can)',
    nameTl: 'Argentina Corned Beef',
    slug: 'argentina-corned-beef',
    descriptionEn: 'Classic corned beef in a can. Perfect for breakfast with garlic rice.',
    descriptionTl: 'Klasikong corned beef sa lata. Bagay pang-almusal na may sinangag.',
    price: 3000,
    image: '/images/products/corned-beef.jpg',
    categorySlug: 'noodles-pantry',
    inventory: 25,
    vendor: "Aling Nena's Sari-Sari",
  },

  // — Candies & Sweets (4) —
  {
    nameEn: 'Choc-Nut (peanut chocolate bar)',
    nameTl: 'Choc-Nut',
    slug: 'chocnut',
    descriptionEn: 'Classic peanut chocolate bar that defines Filipino childhood.',
    descriptionTl: 'Klasikong peanut chocolate bar na tumatak sa pagkabata ng bawat Pinoy.',
    price: 500,
    image: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=600&h=400&fit=crop',
    categorySlug: 'candies',
    inventory: 80,
    vendor: "Aling Nena's Sari-Sari",
  },
  {
    nameEn: 'Mik-Mik (Strawberry)',
    nameTl: 'Mik-Mik (Strawberry)',
    slug: 'mikmik',
    descriptionEn: 'Powdered milk candy in a tiny pouch. Pour directly into your mouth!',
    descriptionTl: 'Powdered milk candy sa maliit na pouch. Diretso sa bibig!',
    price: 300,
    image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=600&h=400&fit=crop',
    categorySlug: 'candies',
    inventory: 100,
    vendor: "Aling Nena's Sari-Sari",
  },
  {
    nameEn: 'Yakee! Super Asim Gumballs',
    nameTl: 'Yakee! Super Asim',
    slug: 'yakee',
    descriptionEn: 'Super sour gumballs. A test of endurance for every kid!',
    descriptionTl: 'Sobrang asim na gumballs. Pagsubok sa bawat bata!',
    price: 100,
    image: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=600&h=400&fit=crop',
    categorySlug: 'candies',
    inventory: 150,
    vendor: "Aling Nena's Sari-Sari",
  },
  {
    nameEn: 'White Rabbit Creamy Candy',
    nameTl: 'White Rabbit Candy',
    slug: 'white-rabbit',
    descriptionEn: 'Chewy milk candy wrapped in edible rice paper. A timeless classic.',
    descriptionTl: 'Malyambot na milk candy na nababalot ng edible rice paper. Tunay na klasiko.',
    price: 200,
    image: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=600&h=400&fit=crop',
    categorySlug: 'candies',
    inventory: 90,
    vendor: "Aling Nena's Sari-Sari",
  },

  // — Beverages (4) —
  {
    nameEn: 'Kopiko Blanca 3-in-1 (sachet)',
    nameTl: 'Kopiko Blanca 3-in-1',
    slug: 'kopiko',
    descriptionEn: 'Classic 3-in-1 coffee with creamer and sugar. Instant energy boost!',
    descriptionTl: 'Klasikong 3-in-1 na kape may creamer at asukal. Instant energy!',
    price: 800,
    image: '/images/products/coffee.jpg',
    categorySlug: 'beverages',
    inventory: 100,
    vendor: "Aling Nena's Sari-Sari",
  },
  {
    nameEn: 'Great Taste White Coffee (sachet)',
    nameTl: 'Great Taste White Coffee',
    slug: 'great-taste',
    descriptionEn: 'Smooth white coffee in a single sachet. A Filipino breakfast staple.',
    descriptionTl: 'Makinis na white coffee sa isang sachet. Pambansang almusal.',
    price: 800,
    image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=600&h=400&fit=crop',
    categorySlug: 'beverages',
    inventory: 80,
    vendor: "Aling Nena's Sari-Sari",
  },
  {
    nameEn: 'Coca-Cola (glass bottle 330ml)',
    nameTl: 'Coca-Cola (bote)',
    slug: 'coke-bote',
    descriptionEn: 'Ice-cold Coca-Cola in the classic glass bottle. Best with any snack!',
    descriptionTl: 'Malamig na Coca-Cola sa klasikong bote. Bagay sa kahit anong meryenda!',
    price: 2000,
    image: 'https://images.unsplash.com/photo-1554866585-cd94860890b7?w=600&h=400&fit=crop',
    categorySlug: 'beverages',
    inventory: 40,
    vendor: "Aling Nena's Sari-Sari",
  },
  {
    nameEn: 'Royal Tru-Orange (330ml)',
    nameTl: 'Royal Tru-Orange',
    slug: 'royal',
    descriptionEn: 'Classic orange soda in a can. The taste of every Filipino party.',
    descriptionTl: 'Klasikong orange soda sa lata. Lasang handaan ng Pinoy.',
    price: 2000,
    image: 'https://images.unsplash.com/photo-1544145945-f90425340c7e?w=600&h=400&fit=crop',
    categorySlug: 'beverages',
    inventory: 35,
    vendor: "Aling Nena's Sari-Sari",
  },

  // — Household Essentials (4) —
  {
    nameEn: 'Surf Powder Detergent (20g sachet)',
    nameTl: 'Surf (sachet)',
    slug: 'surf',
    descriptionEn: 'Classic laundry detergent in a single-use sachet. Tingi-tingi size!',
    descriptionTl: 'Klasikong panglaba sa isang sachet. Tingi-tingi size!',
    price: 500,
    image: 'https://images.unsplash.com/photo-1585421514284-efb74c2b69ba?w=600&h=400&fit=crop',
    categorySlug: 'household',
    inventory: 60,
    vendor: "Aling Nena's Sari-Sari",
  },
  {
    nameEn: 'Privince Shampoo (sachet)',
    nameTl: 'Privince Shampoo',
    slug: 'privince',
    descriptionEn: 'Classic shampoo in a single sachet. Long-lasting clean and fragrance.',
    descriptionTl: 'Klasikong shampoo sa isang sachet. Matagal na linis at bango.',
    price: 500,
    image: 'https://images.unsplash.com/photo-1576618148400-f54bed99fcfd?w=600&h=400&fit=crop',
    categorySlug: 'household',
    inventory: 70,
    vendor: "Aling Nena's Sari-Sari",
  },
  {
    nameEn: 'Safeguard Soap (bar)',
    nameTl: 'Safeguard (bar)',
    slug: 'safeguard',
    descriptionEn: 'Safeguard antibacterial soap, one bar. Everyday protection for the family.',
    descriptionTl: 'Safeguard na antibacterial, isang bar. Pang-araw-araw na proteksyon ng pamilya.',
    price: 1500,
    image: 'https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?w=600&h=400&fit=crop',
    categorySlug: 'household',
    inventory: 50,
    vendor: "Aling Nena's Sari-Sari",
  },
  {
    nameEn: 'Zonrox Bleach (100ml)',
    nameTl: 'Zonrox (100ml)',
    slug: 'zonrox',
    descriptionEn: 'Original Zonrox bleach, small bottle. For whites and disinfection.',
    descriptionTl: 'Zonrox na original, maliit na bote. Pangpaputi at pang-disinfect.',
    price: 1000,
    image: 'https://images.unsplash.com/photo-1584820927498-cfe5211fd8bf?w=600&h=400&fit=crop',
    categorySlug: 'household',
    inventory: 40,
    vendor: "Aling Nena's Sari-Sari",
  },

  // — Biscuits & Snacks (4) —
  {
    nameEn: 'Piattos (Roadhouse Barbecue)',
    nameTl: 'Piattos (Roadhouse BBQ)',
    slug: 'piattos',
    descriptionEn: 'Classic ridge-cut potato chips. The ultimate Filipino snack.',
    descriptionTl: 'Klasikong ridge-cut potato chips. Ang ultimate na meryenda ng Pinoy.',
    price: 1000,
    image: 'https://images.unsplash.com/photo-1495147466023-ac5c588e2e94?w=600&h=400&fit=crop',
    categorySlug: 'biscuits',
    inventory: 35,
    vendor: "Aling Nena's Sari-Sari",
  },
  {
    nameEn: 'Chikadees (Original)',
    nameTl: 'Chikadees (Original)',
    slug: 'chikadees',
    descriptionEn: 'Crunchy corn snack in the iconic red pack. A true classic.',
    descriptionTl: 'Malutong na corn snack sa pulang pack. Tunay na klasiko.',
    price: 500,
    image: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=600&h=400&fit=crop',
    categorySlug: 'biscuits',
    inventory: 45,
    vendor: "Aling Nena's Sari-Sari",
  },
  {
    nameEn: 'X.O. Coffee Candy (each)',
    nameTl: 'X.O. Coffee Candy',
    slug: 'xo-coffee',
    descriptionEn: 'Strong coffee-flavored hard candy. A quick energy fix for any time.',
    descriptionTl: 'Matapang na candy na lasang kape. Pampagising kahit saan.',
    price: 100,
    image: 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=600&h=400&fit=crop',
    categorySlug: 'biscuits',
    inventory: 200,
    vendor: "Aling Nena's Sari-Sari",
  },
  {
    nameEn: 'Kopiko Candy (each)',
    nameTl: 'Kopiko Candy',
    slug: 'kopiko-candy',
    descriptionEn: 'Classic coffee candy. Small but packs a punch of energy.',
    descriptionTl: 'Klasikong kendi na lasang kape. Maliit pero energizer!',
    price: 100,
    image: 'https://images.unsplash.com/photo-1621939514649-280e2ee25f60?w=600&h=400&fit=crop',
    categorySlug: 'biscuits',
    inventory: 200,
    vendor: "Aling Nena's Sari-Sari",
  },
]
